version: "3.9"

services:

  db:
    image: postgres:13.6-alpine
    container_name: dairy-db
    volumes:
      - dairy-db:/var/lib/postgresql/data
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dairy-db

volumes:
  dairy-db:
